### ISSUE TITLE
Signature Doesn't Match Error

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#216]
**Problem**
I assume this is a UI SOPS bug but I'm getting the following error while trying to make a materialization to Firebolt in the UI:

`driver error while validating materialization estuary/monitoring/firebolt-hs-and-fb Caused by: driver.Validate: exit status 1 with stderr: loading materialization spec: downloading existing spec failed: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403, request id: 6F3X2K74DZ13B30N, host id: iv0nlt35RSrnZU/bZuMbI5xsW1Hnoxa8T4ZvUnEIJjoU5Qkdp0AvY/r7Z77+UYxsNV3Gr4ER5rk=`

I've gotten this a bunch of times now intermittently but usually if I change my catalog, regenerate it and try again it works.  Adding @mdibaiee in case it's a problem with the firebolt connector.

This happened for the following draft ID `06:61:ae:4f:29:3b:bc:00`

**Comment by mdibaiee** [comment]
@dyaffe this is actually an issue in the Firebolt connector when it tries to fetch the resources we have put on AWS S3... I'll look into it

**Comment by mdibaiee** [comment]
@dyaffe actually, I can't spot an issue in the code. This error seems to happen mostly when you have wrong credentials. I'm wondering if you had a space before/after the aws key id or secret by any chance? 🤔 

Reading here: https://stackoverflow.com/questions/30518899/amazon-s3-how-to-fix-the-request-signature-we-calculated-does-not-match-the-s

**Comment by mdibaiee** [comment]
I confirmed in case of `06:61:ae:4f:29:3b:bc:00` there was an extra space at the end of aws_secret_key. Dave mentioned some other cases of this happening again, so I'll investigate those cases too.

**Comment by dyaffe** [comment]
Mahdi is right.  This was user error, though I will say it would be nice if the UI stripped whitespace in keys that obviously can't have any
