### ISSUE TITLE
Empty config does not work for capture connector

### ISSUE THREAD

**Issue by mdibaiee** [estuary/ui#392]
**Bug**
We have removed configuration of Hello World source, because it doesn't really need any configuration, it's just an infinite list of Hello Worlds. But this doesn't seem to work with the UI as clicking "Discover" doesn't do anything.

**Expected**
I can click "Discover" and then publish this capture.

**Screenshots**
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/2807772/205051936-05d3bdd2-3039-4f05-bffe-fe20476b01d1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox

**Additional context**

**Comment by kiahna-tucker** [comment]
This connector was updated on Dec. 1, 2022 resulting in an empty _Endpoint Config_ section. Sharing for record-keeping purposes.

<img width="1061" alt="broken_hello_world_source" src="https://user-images.githubusercontent.com/77648584/205950664-016c6a82-558c-4e49-8b46-69032fd581e2.PNG">
