### ISSUE TITLE
Editing Materialization Leads to Error

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#394]
**Bug**
If you either edit a materialization or select the checkbox next to one then select materialize, you receive the following error:

`Error: schema with key or id "https://github.com/estuary/connectors/materialize-rockset/config" already exists at c._checkUnique (https://dashboard.estuary.dev/static/js/772.69de15ee.chunk.js:5:27868) at c._addSchema (https://dashboard.estuary.dev/static/js/772.69de15ee.chunk.js:5:27750) at c.compile (https://dashboard.estuary.dev/static/js/772.69de15ee.chunk.js:5:22437) at https://dashboard.estuary.dev/static/js/137.10057d23.chunk.js:1:8742 at s (https://dashboard.estuary.dev/static/js/137.10057d23.chunk.js:1:8767) at https://dashboard.estuary.dev/static/js/722.1eba346c.chunk.js:1:92679 at zl (https://dashboard.estuary.dev/static/js/main.2eddd502.js:102:573598) at t.unstable_runWithPriority (https://dashboard.estuary.dev/static/js/main.2eddd502.js:102:617862) at Vi (https://dashboard.estuary.dev/static/js/main.2eddd502.js:102:513917) at Ll (https://dashboard.estuary.dev/static/js/main.2eddd502.js:102:573059)
`

I did this by materializing this capture `trial/rockset/test-stripe-data/source-stripe` and editing this materialization `rockset/web_prod_dau`

**Comment by kiahna-tucker** [comment]
An [issue corresponding to this defect](https://github.com/estuary/ui/issues/385) was already created.
