### ISSUE TITLE
Searching for Capture Results in "no shard status found"

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#407]
**Bug**
When I search for a capture or materialization that's not on the first page of results, the entity shows up but with its status bubble black.

**Expected**
We should display the status bubble correctly in this case.

**Comment by kiahna-tucker** [comment]
**UI NOTE:** Shard status is religiously queried on a 30-second interval. If you apply a filter or change entity table pages in production today, it can take up to 30 seconds for a new API call to be made to get the shard statuses for this updated view. Previously, when automated SWR revalidation methods were enabled, filtering the table or changing the table page would prompt the fetching of a new set of shard statuses. That is my current hunch.
