### ISSUE TITLE
Improve Wording of Registration Page

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#491]
**Background**
Our current registration page wording is "Please use a provider below to regisiter for a free trial of Estuary Flow."

There are two issues with it
1. A misspelling 
2. The fact that we allow for free usage (vs free trial).

**Proposal**
Update it to:

"Please login with a provider to use Estuary Flow for free"

**Comment by oliviamiannone** [comment]
Proposed tweak: "log in" with a space because it's used as a verb here.
