### ISSUE TITLE
Update the materialization field selection doc link

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/ui#717]
**Bug**
Field Selector for materializations links to conceptual docs on projections, but a guide has been written on this topic. 

**Expected**
Link to https://docs.estuary.dev/guides/customize-materialization-fields/

<img width="386" alt="image" src="https://github.com/estuary/ui/assets/82397941/fe891033-1859-46a8-b957-23fe4cdb8f7d">

**Comment by kiahna-tucker** [comment]
This is not a defect. Documentation was written after the feature was released and the doc link in the UI needs to be updated.
