### ISSUE TITLE
Disappearing scroll bars in billing make it hard to see what's happening

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#910]
**Problem**
Check out this screenshot.  You'll see that in billing, if you have one more item than matches the size of our table, it won't fit in the table and you won't see a scroll bar to make it obvious that anything is there.

This led to a complaint that our billing was wrong

<img width="1332" alt="Screenshot 2023-12-28 at 11 34 02 AM" src="https://github.com/estuary/ui/assets/8095717/77c59e84-dcbd-4c74-8b1a-128a3b8a61da">

**Comment by kiahna-tucker** [comment]
**ASIDE:** I would expect the header of this table to remain in place while vertically scrolling to preserve context for the column data. Any opposition to that?
