### ISSUE TITLE
Evolutions cause errors in materialization bindings selector

### ISSUE THREAD

**Issue by psFried** [estuary/ui#927]
**Bug**

The steps to repoduce are:
- Start with a materialization of a collection that uses schema inference, and ingest documents such that the inferred schema will have incompatible changes
- Edit the materialization in the UI, and it should automatically display an error and the offer to apply the evolutions job
- Click Apply
- Once the evolution finishes, the bindings editor is replaced by an error: `There was an unexpected application error. Expand to see details.`

The console shows the following error:
```
Uncaught Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{}
    checkGridRowIdIsValid gridRowsUtils.js:27
    getRowIdFromRowModel gridRowsUtils.js:32
    createRowsInternalCache gridRowsUtils.js:49
    useGridRows useGridRows.js:449
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 4
    unstable_runWithPriority scheduler.development.js:468
    React 5
    handleStoreChange use-sync-external-store-shim.development.js:188
    setState vanilla.mjs:9
    setState vanilla.mjs:9
    setState middleware.mjs:56
    evaluateDiscoveredCollections Store.ts:717
    storeDiscoveredCollections useStoreDiscoveredCaptures.ts:105
    waitForEvolutionToFinish SchemaEvolution.tsx:95
    makeApiCall supabase.ts:466
    promise callback*then types.ts:189
    makeApiCall supabase.ts:439
    setTimeout handler*jobStatusPoller supabase.ts:507
    waitForEvolutionToFinish SchemaEvolution.tsx:78
    save SchemaEvolution.tsx:144
...truncated for brevity
```

I found that I'm able to re-fresh the page at this point, and it'll work as normal.

**Expected**

The bindings selector doesn't error

**Screenshots**

<img width="1677" alt="Screen Shot 2024-01-17 at 4 04 25 PM" src="https://github.com/estuary/ui/assets/4495829/67923478-5125-4793-9dbe-b40b54c4ec3b">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: firefox

**Additional context**

I'm thinking this is maybe related to the fact that there's no actual collection in the draft, and the UI is expecting to find one, but that's just a guess. I'm having a little trouble understanding the code here, though. It's using a hook called `useStoreDiscoveredCaptures`, which seemed weird because I'm editing a materialization.
I'm thinking that when this was originally written, we only expected to need evolutions in the context of editing a capture.

**Comment by psFried** [comment]
Attaching a network log here, starting just before clicking "Apply" on the evolution action.
I noticed something weird in there:

- Immediately after we observe the successfully completed evolution, there's a request to fetch the materialization draft spec as expected
- That's followed immediately by a PATCH request to update the same materialization spec
- That's followed immediately by _another_ GET request for the same spec

[network-har.json](https://github.com/estuary/ui/files/13968782/network-har.json)

**Comment by psFried** [comment]
OK, I think I see the issue. [When we update the store](https://github.com/estuary/ui/blob/1ffcc6a7034f50cba8de0d79b7a6ae0ce5354898/src/stores/ResourceConfig/Store.ts#L738), we're assuming that the spec is a capture spec and only grabbing the `target` of each binding. Since this is a materialization, the `target` is undefined, which results in it passing an array with 2 `undefined` elements to `populateCollections`. The `state.collections` ends up being `[undefined, undefined]`, which seems like what's causing the issue. I'm thinking that it might work to just update that code to pull out either `target` or `source` (or `source.name`). WDYT?

Another question, related to those seemingly extra network calls: [This comment](https://github.com/estuary/ui/blob/1ffcc6a7034f50cba8de0d79b7a6ae0ce5354898/src/hooks/useStoreDiscoveredCaptures.ts#L81) was pretty confusing, and I'd like to understand why that section of the code is even there to begin with. It seems to just be taking the response from fetching draft specs, and immediately sending the same specs back in a PATCH request. I feel like I must be missing something. Anyone able to interpret that comment for me?

**Comment by kiahna-tucker** [comment]
> I'm thinking that when this was originally written, we only expected to need evolutions in the context of editing a capture.

Yes, this appears to be the case given the name of the hook and related logic. I would recommend that the hook be renamed and associated comments and code updated to reflect the expanded schema evolution scope.

> I'm thinking that it might work to just update that code to pull out either target or source (or source.name). WDYT?

This the resource config store action, `evaluateDiscoveredCollections`, should be updated to account for the expanded scope (i.e., materialization specification handling). If `setDiscoveredCollections` is used in the schema evolution logic, it will need to be updated as well.

Arguably, I would want to review the all schema evolution related logic to make sure there aren't any other instances capture-coupling.
