### ISSUE TITLE
Enable setting the backfill counter of all task bindings with a single action

### ISSUE THREAD

**Issue by kiahna-tucker** [estuary/ui#962]
**Last Updated:** Feb. 6, 2024

<hr />

Below are the base requirements for this feature:

* Add a _Backfill_ section directly above the bindings selector in edit workflows that contains a header, short description, and an outlined, toggle button with the label _Backfill_. This button should have the same styling as the binding-specific _Backfill_ button.

* Update the backfill counter of applicable, drafted bindings when the new backfill button is clicked. The toggle button state triggers are as follows:
    * **Disabled:** the button will be in a disabled state when an asynchronous task that updates the server is in progress and when the drafted specification does not contain at least one enabled binding.
    
    * **Deselected:** the button will be in a deselected state by **default** and when the backfill counter of any drafted binding **has not** been incremented in the editing session.
    
    * **Selected:** the button will be in a selected state when the backfill counter of all drafted bindings **have** been incremented in the editing session.

**NOTE:** The backfill counter of a drafted binding does **not** need to be _reset_ if the binding is disabled post-incrementation in the editing session.

**Comment by kiahna-tucker** [comment]
## Questions

* What label should be used on the new backfill button (e.g., _Backfill_, _Backfill All_, etc.)?

* The present UX makes it easy to increment the backfill counter of all drafted, bindings, but it does not provide a means to _reset_ the backfill counter of all drafted, bindings. Therefore, I propose that the overarching, _Backfill_ section include a standard, outlined button that will reset the backfill counter of all drafted bindings that **have** been incremented in the editing session. What does everyone think about this proposal? If accepted, what label should be used on the reset button (e.g., _Reset_, _Reset All_, _Undo_, _Undo All_, _Unset_, _Unset All_, etc.)?

**Comment by dyaffe** [comment]
"Backfill" for the button would make sense to me with the subtext "Trigger a backfill of all collections from the source when published."

Just to confirm, when you say "reset the backfill counter", you mean if it was previously 0, someone clicked "backfill" and all bindings went to 1, they could click the button and have them all go back to zero?

Why not make it work like it does at the binding level?  It appears that the button has state and can go back and forth between selected and unselected.  I personally like that UX!

**Comment by kiahna-tucker** [comment]
> Just to confirm, when you say "reset the backfill counter", you mean if it was previously 0, someone clicked "backfill" and all bindings went to 1, they could click the button and have them all go back to zero?

Correct.

> Why not make it work like it does at the binding level? It appears that the button has state and can go back and forth between selected and unselected.

The new backfill button _will_ have the same states as the binding-specific backfill button (i.e., selected, deselected, and disabled). That said, the new backfill button will only appear selected when the backfill counter of **all** drafted bindings **have** been incremented in the editing session. This means that the button will enter a deselected state when the backfill counter of **any** drafted binding **has not** been incremented in the editing session. Consequently, the deselected state of the new backfill button cannot be used to _reset_ the backfill counter of all drafted bindings.

**Comment by kiahna-tucker** [comment]
## Backend Questions

- What consumes and ultimately handles backfilling task bindings?

- How are (binding) counters evaluated? Does the underlying process compare the backfill counter of a binding in the live spec to that of the draft spec and, if incremented, it triggers a backfill? Is incrementing the backfill counter by more than one interpreted differently?

- Are newly added bindings (i.e., bindings that are not present in the live specification) always backfilled? I would imagine so.

- Would it be possible to pass a flag to the publication handler to state that all task bindings should be backfilled?

It would be pretty great if the UI could pass a flag to the publication handler that would prompt backfills of _all_ task bindings because, not only would it simplify the amount of tracked specification state and deep object comparisons the UI would need to perform, the CLI could make use of this function as well (or so I would imagine).

cc: @jgraettinger 

### Initial Responses

I posed these questions to @psFried and his initial responses can be found below.

> What consumes and ultimately handles backfilling task bindings?

The counters are evaluated during the `Apply` rpc. The connector compares the previous and current backfill counters and if they're different at all, it'll drop the associated table (for materializations) and any state that's associated with that binding. That causes it to start from the beginning of the collection history when it starts materializing again.

For captures, it works basically the same, but it just clears out the state, so the connector will start capturing from the beginning.

> How are (binding) counters evaluated? Does the underlying process compare the backfill counter of a binding in the live spec to that of the draft spec and, if incremented, it triggers a backfill? Is incrementing the backfill counter by more than one interpreted differently?

we talked about validating that backfill counters are only incremented, but at present that's not implemented. We should proceed as if we will add that validation, though

> Are newly added bindings (i.e., bindings that are not present in the live specification) always backfilled?

newly added bindings are always backfilled, yeah

> Would it be possible to pass a flag to the publication handler to state that all task bindings should be backfilled?

I don't think we can have the publications handler increment backfill counters. It might be possible to have some other way to trigger such an update, though. Perhaps we could add that behavior to the evolutions handler... :thinking_face: lemme think about that some more

**Comment by dyaffe** [comment]
@kiahna-tucker that's a great question.  Maybe a practical example would help.  If a collection had 3 bindings in the following states when it was opened:
 - Binding 1: backfill 0
 - Binding 2: backfill 1
 - Binding 3: backfill 0
If the user clicks "Backfill" on binding 2 then clicks "Backfill" at the capture level, what should happen?  Ideally we'd be in the following state:
 - Binding 1: backfill 1
 - Binding 2: backfill 2
 - Binding 3: backfill 1
Specifically Binding 2 wouldn't be at backfill 3.  What I wouldn't want to have happen is for binding 2 to be at backfill 3 because then if the user tried to remove backfill on binding 2, they would still get a backfill.  

I don't think it's worthwhile having us try and preserve a "middle state" or offer that which would enable a user to go back to what they've selected before hitting the catpure-level backfill button.  As such, I would propose just two states at the capture level:

"Backfill" -- increments the backfill counter on all bindings from the state when you start editing the capture.
"Un-backfill" (just clicking that button a second time) -- puts state back into the place it was when you open the capture to edit it.

**Comment by kiahna-tucker** [comment]
> I don't think it's worthwhile having us try and preserve a "middle state" or offer that which would enable a user to go back to what they've selected before hitting the capture-level backfill button.

I was not proposing an intermediate state. In a given editing session, a binding backfill counter will only be incremented by one. That has been understood. The tension I was attempting to rectify is exemplified in the following example.

Initial binding state:

B1: `backfill: 0`
B2: `backfill: 0`
B3: `backfill: 0`

Initial, task-level backfill button state: _deselected_

**task-level backfill button clicked**

Binding state:

B1: `backfill: 1`
B2: `backfill: 1`
B3: `backfill: 1`

Task-level backfill button state: _selected_

**B1 binding-level backfill button clicked**

Binding state:

B1: `backfill: 0`
B2: `backfill: 1`
B3: `backfill: 1`

Task-level backfill button state: _deselected_

If a user wanted to _reset_ all the binding backfill counters to their original value -- mirroring the live specification -- they have two options:

1. Click the binding-level backfill button that is in a selected state for each applicable binding.

1. Click the task-level backfill button twice: first to place it in a selected state, then to place it in a deselected state.

The function of the task-level backfill button employs the same UX as a standard, select all button (e.g., selecting all rows of a table) which is how this button should function. I just wanted to call out this UX to level set expectations.

**Comment by dyaffe** [comment]
That makes sense to me @kiahna-tucker
